### ISSUE TITLE
损失函数不能下降

### ISSUE THREAD

**Issue by JiaShengLiu111** [gongpx20069/Machine_Learning#1]
您好，看到您去年的博客：https://bbs.csdn.net/topics/392318704
您提到自己实现的MobileNet训练过程中损失函数时不降反升，不知道您最后是怎么解决的，期待您的回答，感谢！

**Comment by gongpx20069** [comment]
> 您好，看到您去年的博客：https://bbs.csdn.net/topics/392318704
> 您提到自己实现的MobileNet训练过程中损失函数时不降反升，不知道您最后是怎么解决的，期待您的回答，感谢！

是我刚开始时候的问题，现在看来根本不是一个问题，像这么大的网络，本来就需要比较好的GPU，并且训练相当的时间。
